import { Inter } from "next/font/google";
import Head from "next/head";
import React from "react";
import Features from "../components/Features";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>

        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>Embrace Community</title>
      </Head>

      <div className="flex flex-col min-h-screen overflow-hidden">
        <Header />

        <main className="grow">
          <Hero />
          <Features />
        </main>

        <Footer />
      </div>
    </>
  );
}
