import { Inter } from "next/font/google";
import Head from "next/head";
import Footer from "../partials/Footer";
import Header from "../partials/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex flex-col min-h-screen overflow-hidden">
				{/*  Site header */}
				<Header />

				{/*  Page content */}
				<main className="grow">
					{/*  Page illustration */}
					<div
						className="relative max-w-6xl mx-auto h-0 pointer-events-none"
						aria-hidden="true"
					>
						{/* <PageIllustration /> */}
					</div>

					{/*  Page sections */}
					{/* <HeroHome /> */}
					<div className="hidden">{/* <FeaturesBlocks /> */}</div>
					{/* <FeaturesZigZag /> */}
				</main>

				{/*  Site footer */}
				<Footer />
			</div>
		</>
	);
}
